# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/zeto/Projects/study/xyz-viewer/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.importButton = QtWidgets.QPushButton(self.centralwidget)
        self.importButton.setGeometry(QtCore.QRect(100, 50, 100, 30))
        self.importButton.setObjectName("importButton")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportButton.setGeometry(QtCore.QRect(200, 50, 100, 30))
        self.exportButton.setObjectName("exportButton")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(100, 100, 200, 200))
        self.imageLabel.setObjectName("imageLabel")
        self.listBoxLabel = QtWidgets.QLabel(self.centralwidget)
        self.listBoxLabel.setGeometry(QtCore.QRect(100, 320, 200, 30))
        self.listBoxLabel.setObjectName("listBoxLabel")
        self.listBox = QtWidgets.QListWidget(self.centralwidget)
        self.listBox.setGeometry(QtCore.QRect(100, 360, 300, 200))
        self.listBox.setObjectName("listBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 579, 800, 21))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.exportButton.setText(_translate("MainWindow", "Export"))
        self.imageLabel.setText(_translate("MainWindow", "Image Placeholder"))
        self.listBoxLabel.setText(_translate("MainWindow", "Listbox:"))
